-- BISR DQ School Bus Group - Supabase V1.3
-- Fresh install: run this entire script once in Supabase > SQL Editor.
-- bus_votes has NO 4-week retention rule: historic votes remain stored indefinitely; the app only limits what parents can view.
-- Calendar source: BISR Diplomatic Quarter Academic Calendar 2026-2027, updated April 2026.

create extension if not exists pgcrypto;

create table if not exists public.children (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 1 and 60),
  villa_number integer not null check (villa_number between 1 and 9999),
  active_from date not null default current_date,
  active_until date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint children_active_range check (active_until is null or active_until >= active_from - 1)
);

create table if not exists public.bus_votes (
  service_date date not null,
  child_id uuid not null references public.children(id) on delete restrict,
  morning boolean null,
  afternoon boolean null,
  updated_at timestamptz not null default now(),
  primary key (service_date, child_id)
);

create table if not exists public.school_years (
  id bigint generated by default as identity primary key,
  label text not null unique,
  start_date date not null,
  end_date date not null,
  updated_at timestamptz not null default now(),
  constraint school_year_range check (end_date >= start_date)
);

create table if not exists public.school_closures (
  id bigint generated by default as identity primary key,
  start_date date not null,
  end_date date not null,
  label text not null,
  category text not null default 'holiday',
  updated_at timestamptz not null default now(),
  constraint school_closure_range check (end_date >= start_date),
  constraint school_closure_unique unique(start_date,end_date,label)
);

create index if not exists children_villa_idx on public.children(villa_number, name);
create index if not exists bus_votes_date_idx on public.bus_votes(service_date);
create index if not exists school_closures_date_idx on public.school_closures(start_date,end_date);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists children_touch_updated_at on public.children;
create trigger children_touch_updated_at before update on public.children
for each row execute function public.touch_updated_at();

drop trigger if exists school_years_touch_updated_at on public.school_years;
create trigger school_years_touch_updated_at before update on public.school_years
for each row execute function public.touch_updated_at();

drop trigger if exists school_closures_touch_updated_at on public.school_closures;
create trigger school_closures_touch_updated_at before update on public.school_closures
for each row execute function public.touch_updated_at();

-- Atomic vote update: prevents simultaneous parents changing AM/PM from overwriting each other.
create or replace function public.set_bus_vote(
  p_date date,
  p_child_id uuid,
  p_journey text,
  p_value boolean
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_journey not in ('morning','afternoon') then
    raise exception 'Invalid journey';
  end if;

  -- Enforce school-day rules in the database as well as in the UI.
  if extract(dow from p_date) in (5,6) then
    raise exception 'No bus service on Friday or Saturday';
  end if;

  if not exists (
    select 1 from public.school_years y
    where p_date between y.start_date and y.end_date
  ) then
    raise exception 'Date is outside the published BISR school term';
  end if;

  if exists (
    select 1 from public.school_closures c
    where p_date between c.start_date and c.end_date
  ) then
    raise exception 'No bus service on a BISR school closure';
  end if;

  insert into public.bus_votes(service_date, child_id, morning, afternoon)
  values (
    p_date,
    p_child_id,
    case when p_journey='morning' then p_value else null end,
    case when p_journey='afternoon' then p_value else null end
  )
  on conflict (service_date, child_id) do update
  set morning = case when p_journey='morning' then excluded.morning else public.bus_votes.morning end,
      afternoon = case when p_journey='afternoon' then excluded.afternoon else public.bus_votes.afternoon end,
      updated_at = now();
end;
$$;

create or replace function public.add_bus_child(
  p_name text,
  p_villa_number integer,
  p_active_from date
) returns public.children
language plpgsql
security definer
set search_path = public
as $$
declare new_child public.children;
begin
  if char_length(trim(p_name)) < 1 or char_length(trim(p_name)) > 60 then
    raise exception 'Child name is required';
  end if;
  if p_villa_number < 1 or p_villa_number > 9999 then
    raise exception 'Invalid Villa number';
  end if;
  insert into public.children(name, villa_number, active_from)
  values (trim(p_name), p_villa_number, p_active_from)
  returning * into new_child;
  return new_child;
end;
$$;

create or replace function public.remove_bus_child(
  p_child_id uuid,
  p_active_until date
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.children
  set active_until = p_active_until
  where id = p_child_id;
end;
$$;

-- Seed current children. Fixed IDs make this section safe to run again.
insert into public.children(id, name, villa_number, active_from)
values
  ('11111111-1111-4111-8111-111111111111','Maria Alejandra',49,'2026-01-01'),
  ('22222222-2222-4222-8222-222222222222','Nicolas Cortes',49,'2026-01-01'),
  ('33333333-3333-4333-8333-333333333333','Enie Rüscher',75,'2026-01-01'),
  ('44444444-4444-4444-8444-444444444444','Poppy Yap',94,'2026-01-01'),
  ('55555555-5555-4555-8555-555555555555','Amelia Hannesdottir',97,'2026-01-01')
on conflict (id) do nothing;

-- Published BISR DQ 2026-27 pupil term window.
insert into public.school_years(label,start_date,end_date)
values ('2026-2027','2026-08-26','2027-07-03')
on conflict (label) do update set start_date=excluded.start_date,end_date=excluded.end_date;

-- Published BISR DQ 2026-27 closures. Friday/Saturday weekends are calculated in the app.
insert into public.school_closures(start_date,end_date,label,category)
values
  ('2026-09-23','2026-09-23','Saudi National Day','public-holiday'),
  ('2026-10-25','2026-10-29','Half Term','holiday'),
  ('2026-12-13','2026-12-31','Winter Break','holiday'),
  ('2027-02-22','2027-02-22','Saudi Foundation Day','public-holiday'),
  ('2027-03-07','2027-03-11','Eid al-Fitr','public-holiday'),
  ('2027-03-28','2027-04-08','Spring Break','holiday'),
  ('2027-05-16','2027-05-20','Eid al-Adha','public-holiday'),
  ('2027-07-04','2027-07-04','Summer Break begins','holiday')
on conflict (start_date,end_date,label) do update set category=excluded.category;

-- Least-privilege browser access. Browser writes go through the RPC functions above.
alter table public.children enable row level security;
alter table public.bus_votes enable row level security;
alter table public.school_years enable row level security;
alter table public.school_closures enable row level security;

revoke all on public.children from anon, authenticated;
revoke all on public.bus_votes from anon, authenticated;
revoke all on public.school_years from anon, authenticated;
revoke all on public.school_closures from anon, authenticated;
grant select on public.children to anon, authenticated;
grant select on public.bus_votes to anon, authenticated;
grant select on public.school_years to anon, authenticated;
grant select on public.school_closures to anon, authenticated;

drop policy if exists "bus children readable" on public.children;
create policy "bus children readable" on public.children for select to anon, authenticated using (true);

drop policy if exists "bus votes readable" on public.bus_votes;
create policy "bus votes readable" on public.bus_votes for select to anon, authenticated using (true);

drop policy if exists "school years readable" on public.school_years;
create policy "school years readable" on public.school_years for select to anon, authenticated using (true);

drop policy if exists "school closures readable" on public.school_closures;
create policy "school closures readable" on public.school_closures for select to anon, authenticated using (true);

revoke execute on function public.set_bus_vote(date, uuid, text, boolean) from public;
revoke execute on function public.add_bus_child(text, integer, date) from public;
revoke execute on function public.remove_bus_child(uuid, date) from public;
grant execute on function public.set_bus_vote(date, uuid, text, boolean) to anon, authenticated;
grant execute on function public.add_bus_child(text, integer, date) to anon, authenticated;
grant execute on function public.remove_bus_child(uuid, date) to anon, authenticated;

-- Realtime updates across parents' phones.
do $$
begin
  begin alter publication supabase_realtime add table public.children; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.bus_votes; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.school_years; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.school_closures; exception when duplicate_object then null; end;
end $$;
