-- BISR DQ School Bus Group - V1 to V1.1 calendar upgrade
-- Use this only if the V1 children/bus_votes database is already installed.

create table if not exists public.school_years (
  id bigint generated by default as identity primary key,
  label text not null unique,
  start_date date not null,
  end_date date not null,
  updated_at timestamptz not null default now(),
  constraint school_year_range check (end_date >= start_date)
);

create table if not exists public.school_closures (
  id bigint generated by default as identity primary key,
  start_date date not null,
  end_date date not null,
  label text not null,
  category text not null default 'holiday',
  updated_at timestamptz not null default now(),
  constraint school_closure_range check (end_date >= start_date),
  constraint school_closure_unique unique(start_date,end_date,label)
);

create index if not exists school_closures_date_idx on public.school_closures(start_date,end_date);


create or replace function public.set_bus_vote(
  p_date date,
  p_child_id uuid,
  p_journey text,
  p_value boolean
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_journey not in ('morning','afternoon') then
    raise exception 'Invalid journey';
  end if;
  if extract(dow from p_date) in (5,6) then
    raise exception 'No bus service on Friday or Saturday';
  end if;
  if not exists (select 1 from public.school_years y where p_date between y.start_date and y.end_date) then
    raise exception 'Date is outside the published BISR school term';
  end if;
  if exists (select 1 from public.school_closures c where p_date between c.start_date and c.end_date) then
    raise exception 'No bus service on a BISR school closure';
  end if;
  insert into public.bus_votes(service_date, child_id, morning, afternoon)
  values (
    p_date,
    p_child_id,
    case when p_journey='morning' then p_value else null end,
    case when p_journey='afternoon' then p_value else null end
  )
  on conflict (service_date, child_id) do update
  set morning = case when p_journey='morning' then excluded.morning else public.bus_votes.morning end,
      afternoon = case when p_journey='afternoon' then excluded.afternoon else public.bus_votes.afternoon end,
      updated_at = now();
end;
$$;

insert into public.school_years(label,start_date,end_date)
values ('2026-2027','2026-08-26','2027-07-03')
on conflict (label) do update set start_date=excluded.start_date,end_date=excluded.end_date;

insert into public.school_closures(start_date,end_date,label,category)
values
  ('2026-09-23','2026-09-23','Saudi National Day','public-holiday'),
  ('2026-10-25','2026-10-29','Half Term','holiday'),
  ('2026-12-13','2026-12-31','Winter Break','holiday'),
  ('2027-02-22','2027-02-22','Saudi Foundation Day','public-holiday'),
  ('2027-03-07','2027-03-11','Eid al-Fitr','public-holiday'),
  ('2027-03-28','2027-04-08','Spring Break','holiday'),
  ('2027-05-16','2027-05-20','Eid al-Adha','public-holiday'),
  ('2027-07-04','2027-07-04','Summer Break begins','holiday')
on conflict (start_date,end_date,label) do update set category=excluded.category;

alter table public.school_years enable row level security;
alter table public.school_closures enable row level security;
revoke all on public.school_years from anon, authenticated;
revoke all on public.school_closures from anon, authenticated;
grant select on public.school_years to anon, authenticated;
grant select on public.school_closures to anon, authenticated;
drop policy if exists "school years readable" on public.school_years;
create policy "school years readable" on public.school_years for select to anon, authenticated using (true);
drop policy if exists "school closures readable" on public.school_closures;
create policy "school closures readable" on public.school_closures for select to anon, authenticated using (true);

do $$
begin
  begin alter publication supabase_realtime add table public.school_years; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.school_closures; exception when duplicate_object then null; end;
end $$;
